"""
generate_request_dq.py

Run data quality checks on the loan_requests table and write
REQUEST_DATA_QUALITY.md in the project root.

Usage:
    python generate_request_dq.py
"""
import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))
from services import generate_request_quality_report

print("Running request data quality checks...")
report, error = generate_request_quality_report()

if error:
    print(f"ERROR: {error}")
    sys.exit(1)

now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
breakdown = report.get("status_breakdown", {})
breakdown_lines = "\n".join(
    f"  - {status}: {count}" for status, count in sorted(breakdown.items())
) or "  (no records)"

def flag(value, threshold=0):
    return "FAIL" if value > threshold else "OK"

lines = [
    "# Request Data Quality Report",
    f"Generated: {now}",
    "",
    "## Summary",
    f"- Total requests: {report['total_requests']}",
    "",
    "## Checks",
    "",
    f"| Check | Count | Status |",
    f"|-------|-------|--------|",
    f"| Missing borrower username | {report['missing_borrower_username']} | {flag(report['missing_borrower_username'])} |",
    f"| Open requests missing thread URL | {report['open_missing_thread_url']} | {flag(report['open_missing_thread_url'])} |",
    f"| Requests missing amount | {report['missing_amount']} | {flag(report['missing_amount'])} |",
    f"| Open requests older than 10 days | {report['open_older_than_10_days']} | {flag(report['open_older_than_10_days'])} |",
    f"| Funded requests not linked to a loan | {report['funded_not_linked']} | {flag(report['funded_not_linked'])} |",
    f"| Requests linked to missing loans | {report['linked_to_missing_loan']} | {flag(report['linked_to_missing_loan'])} |",
    "",
    "## Status Breakdown",
    "",
    breakdown_lines,
    "",
    "---",
    "_Generated by generate_request_dq.py — read-only, no data modified._",
]

output = "\n".join(lines) + "\n"
out_path = os.path.join(os.path.dirname(__file__), "REQUEST_DATA_QUALITY.md")
with open(out_path, "w", encoding="utf-8") as f:
    f.write(output)

print(f"Report written to: {out_path}")

# Print summary to stdout
fails = [
    k for k in [
        "missing_borrower_username", "open_missing_thread_url", "missing_amount",
        "open_older_than_10_days", "funded_not_linked", "linked_to_missing_loan",
    ]
    if report.get(k, 0) > 0
]
if fails:
    print(f"\n{len(fails)} check(s) need attention:")
    for k in fails:
        print(f"  - {k}: {report[k]}")
else:
    print("All checks passed.")
