import re
import logging
import traceback

logger = logging.getLogger("LoanCentral")

# Command trigger - this will be used by the CommandManager
COMMAND_TRIGGER = "$mods"

def process_mods_command(comment):
    """Process the $mods command to notify moderators"""
    # Import here to avoid circular imports
    from utils import reddit
    
    if not "$mods" in comment.body.lower():
        return
    
    try:
        # Get the username who called the mods
        username = comment.author.name
        
        # Get the subreddit from the comment
        post_subreddit = comment.submission.subreddit.display_name
        subreddit = reddit.subreddit(post_subreddit)
        
        # Extract any additional message (optional)
        message_match = re.search(r'\$mods\s+(.+)', comment.body, re.IGNORECASE | re.DOTALL)
        additional_message = message_match.group(1).strip() if message_match else "No additional message provided."
        
        # Send modmail
        subject = f"Moderator Request from u/{username}"
        message = f"""
A user has requested moderator attention:

**User:** u/{username}
**Thread:** https://www.reddit.com{comment.permalink}
**Post Title:** {comment.submission.title}

**User's Message:**
{additional_message}

---
This notification was generated by the LoanCentral Bot in response to a $mods command.
        """
        
        subreddit.message(subject, message)
        
        # Reply to the user
        comment.reply(f"Thank you u/{username}, I've notified the moderators. They will review your request as soon as possible.")
        
        logger.info(f"Moderator notification sent from user {username}")
        
    except Exception as e:
        logger.error(f"Error processing mods command: {e}")
        logger.error(traceback.format_exc())
        try:
            comment.reply("Error notifying moderators. Please message the moderators directly.")
        except:
            pass